### ISSUE TITLE
Licença

### ISSUE THREAD

**Issue by braully** [joaotux/pdv#10]
Qual a licença desse projeto? Se não  possui nenhuma, sugiro a MIT ou Apache 2. Tenho interesse em contribuir no projeto, mas gostaria de ter uma licença livre definida.

**Comment by joaotux** [comment]
Ola Braully, este projeto é 100% livre, não adicionai nenhuma licença pois não trabalho mais nele, mas vou adicionar umas das licenças sugeridas por você.

**Comment by joaotux** [comment]
Como sugerido, foi adicionado ao projeto a licença Apache 2, muito obrigado pela sugestão Braully, e mesmo eu não trabalhando mais neste projeto, fico feliz de ver ele andando com a ajuda de outros desenvolvedores.

**Comment by braully** [comment]
Otima escolha. Obrigado
